location:
    latitude: '42.262380'
    longitude: '-88.127720'
    elevation: 240
logging:
    level: DEBUG
    filename: quackhouse.log
    format: '%(asctime)s [%(levelname)s] (%(threadName)-10s) %(message)s'
pi:
    forward_pin: 26
    backward_pin: 20
door:
    duration: 60
    open_elevation: 6
    close_elevation: -9